name: ENV Variables
on: push
env:
  WF_ENV: Available to all jobs

jobs:
  logs-env:
    runs-on: ubuntu-latest
    env:  
      JOB_ENV: Available to all steps in logs-env
    steps:  
      - name: log ENV Variables
        env:
          STEP_ENV: Available to this step
        run: |
          echo "WF_ENV:{WF_ENV}"
          echo "JOB_ENV:{JOB_ENV}"
          echo "STEP_ENV:{STEP_ENV}"