name: shell commands

on: 
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/3 * * 8 1"

  pull_request:
    types: [closed, opened, assigned, reopened]

jobs:
  run-shell-command: 
    runs-on: windows-latest
    if: github.ref == 'master'
    steps:
      - name: echo a string
        run: echo "hello Nidhi!!"
      - name: multiline script
        run: |
          node -v
          npm -v
          

          

