name: Upload-artficats
on: push

jobs:
  builds:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "hello!!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./index.html
