name: Upload-artficats
on: push

jobs:
  builds:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "hello!!"
      - name: multiline script
        run: |
          node -v
          npm -v

