name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:16-alpine
    steps: 
      - name: Log node version
        run: |
          node -v 
          cat /etc/os-release
  node-docker-job:
    runs-on: ubuntu-latest
    services: 
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "8081:8081"
    steps: 
      - name: echo
        run: echo "docker container"
      - name: ports
        run: 'curl -X POST http://localhost:3001/api/user

          -H ''Content-Type: application/json'' -d ''

          {"username": "hello","address": "dwded"}"'
      - name: Get users
        run: curl http://localhost:3001/api/users   
        