name: Action Workflow

on: 
  repository_dispatch:
    types: [build]

  pull_request:
    types: [closed, assigned, opened, reopened]

    

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "dispatch repository"
