name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps: 
      - name: log node version
        run: node -v
      - name: Step1 with docker
        uses: docker://mongodb:mongo
        with:
          entrypoint: '/bin/echo'
          args: 'Hello world'
      - name: Step2 with docker
        uses: docker://mongodb:mongo
        with:
          entrypoint: '/cmd/git'
          args: -v



