name: Formatting secret
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true  
        default: staging  
      publish_profile : 
        type: string
        required: true  
      db_name : 
          type: string
          required: true  

    secrets:
      PUBLISH_PROFILE_SECRET:
        required: false

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: writing secrets to file
        run: |
          echo "Publish profile: ${{ secrets.PUBLISH_PROFILE_SECRET }}"
          echo "inputs secret publish profile var name: ${{ inputs.publish_profile }}"
          echo "inputs db name  : ${{ inputs.db_name }}"
          echo "${{ secrets.PUBLISH_PROFILE_SECRET }}" > ${{ github.workspace }}/my_secret_${{ inputs.publish_profile }}.txt
          cat ${{ github.workspace }}/my_secret_${{ inputs.publish_profile }}.txt

      - name: Archive Secret File
        run: zip secret_archive_${{ inputs.publish_profile }}.zip ${{ github.workspace }}/*

      - name: Upload a Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive_${{ inputs.publish_profile }}.zip
