name: Formatting secret
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true  
        default: staging  
      secret_var : 
        type: string
        required: true  
      db_name : 
          type: string
          required: false  
    secrets:
      PUBLISH_PROFILE_SECRET:
        required: false

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: writing secrets to file
        run: |
          echo "Publish profile: ${{ secrets.PUBLISH_PROFILE_SECRET }}"
          echo "inputs secret publish profile var name: ${{ inputs.secret_var }}"
          echo ${{ secrets.PUBLISH_PROFILE_SECRET }} > ${{ github.workspace }}/my_secret_${{ inputs.secret_var }}.txt
          cat ${{ github.workspace }}/my_secret_${{ inputs.secret_var }}.txt

      - name: Archive Secret File
        run: zip secret_archive_${{ inputs.secret_var }}.zip ${{ github.workspace }}/my_secret_${{ inputs.secret_var }}.txt

      - name: Upload a Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive_${{ inputs.secret_var }}.zip
