name: Formatting secret
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true  
        default: staging    
    secrets:
      PUBLISH_PROFILE:
        required: true

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
        with:
          publish_profile: ${{ secrets.PUBLISH-PROFILE }}

      - name: 'Echoing secret'
        run: echo "Secret name is $publish_profile  "




