name: Formatting secret
on: 
  workflow_call:
    secrets:
      PUBLISH-PROFILE:
        required: true

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 'Added a secret'
        uses: actions/checkout@v2
        with:
          publish_profile: ${{ secrets.PUBLISH-PROFILE }}

      - name: 'Echoing secret'
        run: echo "Secret name is $publish_profile  "




