name: Formatting secret
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true  
        default: staging    
    secrets:
      PUBLISH_PROFILE_SECRET:
        required: true

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: writing secrets to file
        run: |
          echo "${{secrets.PUBLISH_PROFILE_SECRET}}" > ${{ github.workspace }}/my_secret.txt
          echo "${{ format('${0}{1}{2}{3}{4}{5}', '{' ,'{','secrets.', 'PUBLISH_PROFILE', '}','}') }} " > ${{ github.workspace }}/formatted_secret.txt

      - name: Archive Secret File
        run: zip secret_archive.zip ${{ github.workspace }}/*

      - name: Upload a Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive.zip

      # - name: 'Echoing secret'
      #   run: |
      #     echo "Secret name is ${{ secrets.PUBLISH_PROFILE_SECRET }}"
      #     echo ${{ secrets.PUBLISH_PROFILE_SECRET }} | sed 's/./& /g'

