name: Formatting secret
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true  
        default: staging  
      app-name:
        type: string
        required: true          
      publish-profile : 
        type: string
        required: true  
        default: staging
      spring-db-name:  
        type: string
        required: true  
    secrets:
      PUBLISH_PROFILE_SECRET:
        required: false

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: writing secrets to file
        run: |
          echo "Publish profile: ${{ secrets.PUBLISH_PROFILE_SECRET }}"
          echo "inputs app name: ${{ inputs.app-name }}"
          echo "inputs publish profile: ${{ inputs.publish-profile }}"
          echo "inputs db name: ${{ inputs.spring-db-name }}"
          echo ${{ secrets.PUBLISH_PROFILE_SECRET }} > ${{ github.workspace }}/my_secret_${{ inputs.publish-profile }}.txt
          cat ${{ github.workspace }}/my_secret_${{ inputs.publish-profile }}.txt

      - name: Archive Secret File
        run: zip secret_archive_${{ inputs.publish-profile }}.zip ${{ github.workspace }}/my_secret_${{ inputs.publish-profile }}.txt

      - name: Upload a Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive_${{ inputs.publish-profile }}.zip