name: Formatting secret
on: 
  push:
    # secrets:
    #   PUBLISH-PROFILE:
    #     required: true

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 'Added a secret'
        uses: actions/checkout@v2
        with:
          publish-profile: ${{ format('{0}{1}', 'secrets.', 'PUBLISH_PROFILE') }}

      - name: 'Echoing secret'
        run: echo "Secret name is $publish-profile  "




