name: Formatting secret
on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true  
        default: staging    
    secrets:
      PUBLISH_PROFILE_SECRET:
        required: true

jobs:
  format-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: writing secrets to file
        run: |
          echo "${{secrets.PUBLISH_PROFILE_SECRET}}" > ${{ github.workspace }}/my_secret.txt

      - name: Archive Secret File
        run: zip secret_archive.zip ${{ github.workspace }}/my_secret.txt

      - name: Upload a Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive.zip
