name: Main workflow
on: push 
env:
  SECRET_VAL: temp val
jobs:
  step1:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      matrix: ${{ steps.matrix_setup.outputs.value }}    
    steps:
    - name: Setup
      id: matrix_setup
      run: echo "value=$(jq -r -c . <<< '${{vars.TENANT_DETAILS}}')" >> $GITHUB_OUTPUT

  # step2:

  #   needs: [step1]
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   # outputs:
  #   #   SECRET: ${{ steps.check_id.outputs.SECRET }}
  #   strategy:
  #     matrix: 
  #       include: ${{ fromJSON(needs.step1.outputs.matrix) }}

  #   steps:
  #   - name: Check
  #     id: check_id                                                                                                                                                                          
  #     run: |
  #       echo "MATRIX: ${{ toJSON(matrix) }}"
  #       echo "APPNAME:${{ join(fromJSON(toJSON(matrix)).tenant_details.*.app-name, ', ') }}"
  #       echo "PUBLISH_PROFILE:${{ join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ') }}"
  #       echo "DATABASE_NAME:${{ join(fromJSON(toJSON(matrix)).tenant_details.*.spring-datasource-url, ', ') }}"
  #   # - name: test
  #   #   run: |
  #   #     echo "secret value:  ${{ secrets[format('{0}' ,join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', '))] }}"

  Secret_format_job:
    needs: [step1]
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.step1.outputs.matrix) }}
    uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
    with:
      environment: staging
      publish_profile: ${{ join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ') }}
      db_name: ${{ join(fromJSON(toJSON(matrix)).tenant_details.*.spring-datasource-url, ', ') }}
    secrets:
      PUBLISH_PROFILE_SECRET: ${{ secrets[join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ')] }}











          

      