name: Main workflow
on: push 
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      First_Name: Mona    
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting ${First_Name}!"

      - name: "Run child workflow"
        uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
        with:
          PUBLISH_PROFILE: ${{ format('{0}{1}', 'secrets.', 'PUBLISH_PROFILE') }}
          

      