name: Main workflow
on: push 
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      First_Name: Mona    
  Secret_format_job:
    uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
    with:
      environment: staging
    secrets:
      PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE }}



          

      