name: Main workflow
on: push 
env:
  SECRET_VAL: temp val
jobs:
  step1:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      matrix: ${{ steps.matrix_setup.outputs.value }}    
    steps:
    - name: Setup
      id: matrix_setup
      run: echo "value=$(jq -r -c . <<< '${{vars.serviceDetails}}')" >> $GITHUB_OUTPUT

  # step2:
  #   needs: [step1]
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   strategy:
  #     matrix: 
  #       include: ${{ fromJSON(needs.step1.outputs.matrix) }}

  Secret_format_job:
    needs: [step1]
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.step1.outputs.matrix) }}
    uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
    with:
      environment: staging
      app-name: ${{ join(fromJSON(toJSON(matrix)).serviceDetails.*.appName, ', ') }}
      publish-profile: ${{ join(fromJSON(toJSON(matrix)).serviceDetails.*.publish-profile, ', ') }}
      spring-db-name: ${{ join(fromJSON(toJSON(matrix)).serviceDetails.*.springDatasourceUrl, ', ') }}
    secrets:
      PUBLISH_PROFILE_SECRET: ${{ secrets[join(fromJSON(toJSON(matrix)).serviceDetails.*.publish-profile, ', ')] }}
