name: Main workflow
on: push 
jobs:

  step1:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      matrix: ${{ steps.matrix_setup.outputs.value }}    
    steps:
    - name: Setup
      id: matrix_setup
      run: echo "value=$(jq -r -c . <<< '${{vars.TENANT_DETAILS}}')" >> $GITHUB_OUTPUT

  step2:
    needs: [step1]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.step1.outputs.matrix) }}

    steps:
    - name: Check
      id: check_id
      run: |
        echo "MATRIX: ${{ toJSON(matrix) }}"
        echo "APPNAME:${{ join(fromJSON(toJSON(matrix)).tenant_details.*.app-name, ', ') }}"
        echo "PUBLISH_PROFILE=${{ join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ') }}">> $GITHUB_ENV 

    
    - name: test
      run: |
        echo "env var:  ${{ secrets[format('{0}' ,join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', '))] }}"
  #       echo ${{ secrets[env.PUBLISH_PROFILE_SECRET] }}
  # Secret_format_job:
  #   needs: [step2]
  #   uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
  #   with:
  #     environment: staging
  #   secrets:
  #     PUBLISH_PROFILE_SECRET: ${{ secrets[env.PUBLISH_PROFILE] }}
        # run: echo " value of publish profile is ${{ env.PUBLISH_PROFILE }}"







          

      