name: Main workflow
on: push 
jobs:

  step1:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      matrix: ${{ steps.matrix_setup.outputs.value }}    
    steps:
    - name: Setup
      id: matrix_setup
      run: echo "value=$(jq -r -c . <<< '${{vars.TENANT_DETAILS}}')" >> $GITHUB_OUTPUT

  step2:
    needs: [step1]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.step1.outputs.matrix) }}

    steps:
    # - name: get secret
    #   uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
    #   with:
    #     environment: staging
    #     PUBLISH_PROFILE: ${{ join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ') }} 
    #     PUBLISH_PROFILE_SECRET: ${{ secrets[format('{0}' , '$PUBLISH_PROFILE')] }}
    - name: Check
      id: check_id
      # env:
      #   MATRIX: ${{ toJSON(matrix) }}
      #   APP_NAME: ${{ join(fromJSON(toJSON(matrix)).tenant_details.*.app-name, ', ') }}
      #   PUBLISH_PROFILE: ${{ join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ') }}     
      #   PUBLISH_PROFILE_SECRET: ${{ secrets[format('{0}' , env.PUBLISH_PROFILE)] }}  
      run: |
        echo "MATRIX: ${{ toJSON(matrix) }}"
        echo "APPNAME: ${{ join(fromJSON(toJSON(matrix)).tenant_details.*.app-name, ', ') }}"
        echo "PUBLISH_PROFILE= ${{ secrets[format(join(fromJSON(toJSON(matrix)).tenant_details.*.publish-profile, ', ') )]}}" >> $GITHUB_ENV

  Secret_format_job:
    runs-on: ubuntu-latest
    needs: [step2]
    steps:
      - name: use env var
        run: echo " value of publish profile is ${{ env.PUBLISH_PROFILE }}"
    # uses: Nidhi-Patel20/Git-Practice/.github/workflows/format-secret.yml@main
    # with:
    #   environment: staging
    # secrets:
    #   PUBLISH_PROFILE_SECRET: ${{ env.PUBLISH_PROFILE }}






          

      