name: Matrix
on: push

jobs:
  node-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [6,8,10]
        include:
          - os : macos-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 6
  
    steps:
      - name: Log node node version
        run: node -v
      - uses:  actions/setup-node@v3
        with:
          node-version: ${{matrix.node_verison}}
      - name: Log node node version
        run: node -v