name: Running matrix

on: push
# env:
#   JSON_VALUE: '{ "name":"package-a", "enabled": "true" }'

jobs:

  setup:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - id: matrix
        run: |
          echo 'value::[ \"${vars.MATRIX_VAR}\"]'>> GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # value: ${{ needs.setup.outputs.matrix }}
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo " Matrix env var: ${{vars.MATRIX_VAR}}"
          echo " Matrix: ${{ matrix.value }}"