name: Running matrix

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo 'Matrix env var is: ${{vars.MATRIX_VAR}} '
#          echo '::set-output name=value::["${{vars.MATRIX_VAR}}"]'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"