name: Running matrix

on: push
# env:
#   JSON_VALUE: '{ "name":"package-a", "enabled": "true" }'

jobs:

  setup:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - id: matrix
        run: |
          echo "value::[${MATRIX_VAR}]">> GITHUB_OUTPUT
        env:
          MATRIX_VAR: ${{vars.MATRIX_VAR}}

          # A: ${{ steps.matrix.outputs.json && fromJSON(steps.matrix.outputs.json).package }}
        
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # value: ${{ needs.setup.outputs.matrix }}
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo " Matrix env var: ${{vars.A}}"
          echo " Matrix: ${{ matrix.value }}"