name: ActionsWorkflow

on: [push, pull_request] 

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY 
      