name: shell commands

on: 
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-shell-command: 
    runs-on: windows-latest
    if: github.ref == 'master'
    steps:
      - name: echo a string
        run: echo "hello Nidhi!!"
      - name: multiline script
        run: |
          node -v
          npm -v
          

          

