name: shell commands

on: 
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo"Thid id the "
      - name: multiline script
        run: |
          node -v
          npm -v


          

