name: env variables
on: push
env:
  WF_ENV: available to all jobs

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: decrypt file
        run: gpg --quiet --batch --yes --decrypt 
          --passphrase="$PASSPHRASE" --output $HOME/secretFile.json 
          secretFile.json.gpg
        env: 
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: print file
        run: cat $HOME/secretFile.json

  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env job
    steps:
      - name: log ENV variables 
        env:
          STEP_ENV: Available to only this step
        run: |
          echo "HOME: ${HOME}"
          echo "WF_ENV: ${{ secrets.WF_ENV }}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
