name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps: 
      - name: log node version
        run: node -v
      - name: Step1 with docker
        uses: docker://node:gallium-alpine3.15
        with:
          entrypoint: '/bin/echo'
          args: 'Hello world'
      - name: Step2 with docker
        uses: docker://node:gallium-alpine3.15
        with:
          entrypoint: '/bin/echo'
          args: -v
      - uses : actions/checkout@v1
      - name: slack message
        uses: docker:technosophos/slack-notify
        env:
          SLACK_WEBHOOK:
          SLACK_MESSAGE: "THIS IS SLACK MESSAGE "


