name: Archive Secret Workflow

on:
  push:
    branches:
      - main

jobs:
  archive_secret:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Write Secret to File
        run: echo "${{ secrets.PUBLISH_PROFILE }}" > ${{ github.workspace }}/my_secret.txt

      - name: Archive Secret File
        run: zip secret_archive.zip ${{ github.workspace }}/my_secret.txt

      - name: Upload a Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive.zip