name: Archive Secret Workflow

on:
  push:
    branches:
      - main

jobs:
  archive_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Write Secret to File
        run: echo "${{ secrets.PUBLISH_PROFILE }}" > my_secret.txt

      - name: Archive Secret File
        run: zip secret_archive.zip my_secret.txt