name: Archive Secret Workflow

on:
  push:
    branches:
      - main

jobs:
  archive_secret:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Write Secret to File
        run: |
          echo "${{ format('${0}{1}{2}{3}{4}{5}', '{' ,'{','secrets.', 'PUBLISH_PROFILE', '}','}') }} " > ${{ github.workspace }}/my_secret.txt
          cat ${{ github.workspace }}/my_secret.txt
#          echo "${{ secrets.PUBLISH_PROFILE }}" > ${{ github.workspace }}/my_secret.txt
          

      - name: Archive Secret File
        run: zip secret_archive.zip ${{ github.workspace }}/my_secret.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: ${{ github.workspace }}/secret_archive.zip